create schema product;
set schema 'product';

DROP TABLE IF EXISTS product;
truncate table product restart identity cascade;

select * from product order by id desc;

CREATE TABLE product (
	id int4 NOT NULL,
	"name" varchar(255) NULL,
	price int4 NOT NULL,
	category varchar(255) NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id)
);

INSERT INTO product(id, name, category, price)
VALUES
(1,'Chais',lower('Beverages'),round(18)),
(2,'Chang',lower('Beverages'),round(19)),
(3,'Aniseed Syrup',lower('Condiments'),round(10)),
(4,'Chef Anton`s Cajun Seasoning',lower('Condiments'),round(22)),
(5,'Chef Anton`s Gumbo Mix',lower('Condiments'),round(21.35)),
(6,'Grandma`s Boysenberry Spread',lower('Condiments'),round(25)),
(7,'Uncle Bob`s Organic Dried Pears',lower('Produce'),round(30)),
(8,'Northwoods Cranberry Sauce',lower('Condiments'),round(40)),
(9,'Mishi Kobe Niku',lower('MeatPoultry'),round(97)),
(10,'Ikura',lower('Seafood'),round(31)),
(11,'Queso Cabrales',lower('DairyProducts'),round(21)),
(12,'Queso Manchego La Pastora',lower('DairyProducts'),round(38)),
(13,'Konbu',lower('Seafood'),round(6)),
(14,'Tofu',lower('Produce'),round(23.25)),
(15,'Genen Shouyu',lower('Condiments'),round(15.5)),
(16,'Pavlova',lower('Confections'),round(17.45)),
(17,'Alice Mutton',lower('MeatPoultry'),round(39)),
(18,'Carnarvon Tigers',lower('Seafood'),round(62.5)),
(19,'Teatime Chocolate Biscuits',lower('Confections'),round(9.2)),
(20,'Sir Rodney`s Marmalade',lower('Confections'),round(81)),
(21,'Sir Rodney`s Scones',lower('Confections'),round(10)),
(22,'Gustaf`s Knäckebröd',lower('GrainsCereals'),round(21)),
(23,'Tunnbröd',lower('GrainsCereals'),round(9)),
(24,'Guaraná Fantástica',lower('Beverages'),round(4.5)),
(25,'NuNuCa Nuß-Nougat-Creme',lower('Confections'),round(14)),
(26,'Gumbär Gummibärchen',lower('Confections'),round(31.23)),
(27,'Schoggi Schokolade',lower('Confections'),round(43.9)),
(28,'Rössle Sauerkraut',lower('Produce'),round(45.6)),
(29,'Thüringer Rostbratwurst',lower('MeatPoultry'),round(123.79)),
(30,'Nord-Ost Matjeshering',lower('Seafood'),round(25.89)),
(31,'Gorgonzola Telino',lower('DairyProducts'),round(12.5)),
(32,'Mascarpone Fabioli',lower('DairyProducts'),round(32)),
(33,'Geitost',lower('DairyProducts'),round(2.5)),
(34,'Sasquatch Ale',lower('Beverages'),round(14)),
(35,'Steeleye Stout',lower('Beverages'),round(18)),
(36,'Inlagd Sill',lower('Seafood'),round(19)),
(37,'Gravad lax',lower('Seafood'),round(26)),
(38,'Côte de Blaye',lower('Beverages'),round(263.5)),
(39,'Chartreuse verte',lower('Beverages'),round(18)),
(40,'Boston Crab Meat',lower('Seafood'),round(18.4)),
(41,'Jack`s New England Clam Chowder',lower('Seafood'),round(9.65)),
(42,'Singaporean Hokkien Fried Mee',lower('GrainsCereals'),round(14)),
(43,'Ipoh Coffee',lower('Beverages'),round(46)),
(44,'Gula Malacca',lower('Condiments'),round(19.45)),
(45,'Røgede sild',lower('Seafood'),round(9.5)),
(46,'Spegesild',lower('Seafood'),round(12)),
(47,'Zaanse koeken',lower('Confections'),round(9.5)),
(48,'Chocolade',lower('Confections'),round(12.75)),
(49,'Maxilaku',lower('Confections'),round(20)),
(50,'Valkoinen suklaa',lower('Confections'),round(16.25)),
(51,'Manjimup Dried Apples',lower('Produce'),round(53)),
(52,'Filo Mix',lower('GrainsCereals'),round(7)),
(53,'Perth Pasties',lower('MeatPoultry'),round(32.8)),
(54,'Tourtière',lower('MeatPoultry'),round(7.45)),
(55,'Pâté chinois',lower('MeatPoultry'),round(24)),
(56,'Gnocchi di nonna Alice',lower('GrainsCereals'),round(38)),
(57,'Ravioli Angelo',lower('GrainsCereals'),round(19.5)),
(58,'Escargots de Bourgogne',lower('Seafood'),round(13.25)),
(59,'Raclette Courdavault',lower('DairyProducts'),round(55)),
(60,'Camembert Pierrot',lower('DairyProducts'),round(34)),
(61,'Sirop d`érable',lower('Condiments'),round(28.5)),
(62,'Tarte au sucre',lower('Confections'),round(49.3)),
(63,'Vegie-spread',lower('Condiments'),round(43.9)),
(64,'Wimmers gute Semmelknödel',lower('GrainsCereals'),round(33.25)),
(65,'Louisiana Fiery Hot Pepper Sauce',lower('Condiments'),round(21.05)),
(66,'Louisiana Hot Spiced Okra',lower('Condiments'),round(17)),
(67,'Laughing Lumberjack Lager',lower('Beverages'),round(14)),
(68,'Scottish Longbreads',lower('Confections'),round(12.5)),
(69,'Gudbrandsdalsost',lower('DairyProducts'),round(36)),
(70,'Outback Lager',lower('Beverages'),round(15)),
(71,'Fløtemysost',lower('DairyProducts'),round(21.5)),
(72,'Mozzarella di Giovanni',lower('DairyProducts'),round(34.8)),
(73,'Röd Kaviar',lower('Seafood'),round(15)),
(74,'Longlife Tofu',lower('Produce'),round(10)),
(75,'Rhönbräu Klosterbier',lower('Beverages'),round(7.75)),
(76,'Lakkalikööri',lower('Beverages'),round(18)),
(77,'Original Frankfurter grüne Soße',lower('Condiments'),round(13));